---
collections:
  - name: cisco.nxos
    version: 2.8.0
  - name: cisco.ucs
#    version: 2.1.0
  - name: cisco.fmcansible
#    version: 1.0.21
  - name: community.vmware
    version: 1.12.0
  - name: community.windows
    version: 1.9.0
  - name: ansible.windows
    version: 1.0.1
  - name: community.general
    version: 3.6.0
  - name: community.kubernetes
    version: 2.3.0
