---
collections:
  - name: cisco.nxos
    version: 4.3.0
  - name: cisco.ucs
    version: 1.8.0
  - name: cisco.fmcansible
#    version: 0.9.0
  - name: community.vmware
    version: 3.6.0
  - name: community.windows
    version: 1.13.0
  - name: ansible.windows
    version: 1.14.0
  - name: community.general
    version: 7.0.0
  - name: community.kubernetes
    version: 2.0.1
