- name: Verificar conectividad y cambiar hostname en Cisco IOS
  hosts: cisco
  gather_facts: no
  collections:
     - cisco.ios
  connection: network_cli
  tasks:
    - name: Hacer ping desde el controlador a 192.168.122.190
      ansible.builtin.shell: ping -c 2 192.168.122.190
      register: resultado_ping
      delegate_to: localhost
      ignore_errors: yes

    - name: Mostrar resultado del ping
      debug:
        var: resultado_ping.stdout

    - name: Cambiar hostname en dispositivo Cisco
      ios_config:
        lines:
          - hostname milton_ansible24

