# ping_icmp.yml
- name: Hacer ping ICMP a 192.168.122.228
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Hacer ping con shell
      ansible.builtin.shell: ping -c 2 192.168.122.228
      register: resultado_ping
      ignore_errors: yes

    - name: Mostrar resultado del ping
      debug:
        var: resultado_ping.stdout
