# cisco_ping_and_hostname.yml
- name: Verificar conectividad y cambiar hostname en Cisco IOS
  hosts: 192.168.122.228
  gather_facts: no
  collections:
  - name: cisco.ios
  connection: network_cli
  tasks:
    - name: Hacer ping desde el controlador a 192.168.122.228
      ansible.builtin.shell: ping -c 2 192.168.122.228
      register: resultado_ping
      delegate_to: localhost
      ignore_errors: yes

    - name: Mostrar resultado del ping
      debug:
        var: resultado_ping.stdout

    - name: Cambiar hostname en dispositivo Cisco
      cisco.ios.ios_config:
        lines:
          - hostname milton_ansible
