---
- name: Verificacion de status de agente elastic Windows
  hosts: all
  vars:
    status_ok: 'Status: HEALTHY'
    cert_thumbprint: 460bac6411726f1fd2a321dffbd976df6a603226
    cert_src_path: ./Certificado_ELK/ca.crt # nombre de certificado MUST be ca.crt
  tasks:

    - name: Validar si elastic agente se encuentra instalado
      ignore_errors: true
      ansible.windows.win_service:
        name: Elastic Agent
        start_mode: auto
        state: started
      register: elastic

    - name: Validar si certificado esta instalado
      community.windows.win_certificate_info:
        store_name: Root
        thumbprint: '{{ cert_thumbprint }}'
      register: ca

    - name: Copiar Certificado en Servidor
      ansible.windows.win_copy:
        src: '{{ cert_src_path }}'
        dest: C:\Temp\
      when: not ca.exists

    - name: Instalar CA en Servidor
      # become: yes
      # become_method: runas
      # become_user: SYSTEM
      ansible.windows.win_certificate_store:
        path: C:\Temp\ca.crt
        file_type: pem
        store_location: LocalMachine
        store_name: Root
        key_storage: machine
        state: present
      when: not ca.exists

    # - name: Verificar reachability a Elastic Search y Fleet Server

    # - name: Configurar DNS
      # ansible.windows.win_dns_client:
        # adapter_names: '*'
        # dns_servers:
        # - 172.25.10.25
        # log_path: C:\dns_log.txt

    - name: Revisar status elastic-agent Powershell
      become: true
      become_method: runas
      become_user: SYSTEM
      ansible.windows.win_powershell:
        script: |
          cd "C:\Program Files\Elastic\Agent\"
          .\elastic-agent.exe status
      register: elastic_status

    - name: Reiniciar Servicio de Elastic Agent
      ansible.windows.win_service:
        name: Elastic Agent
        start_mode: auto
        state: restarted
      when: elastic_status.output[0] != status_ok

    - name: Send notification message via MS Teams
      community.general.office_365_connector_card:
        webhook: https://harsomx.webhook.office.com/webhookb2/bf693546-8702-4185-9fbe-2ea27a6b65d7@40b6f753-6e95-4c0a-bd92-a9fcb653746a/IncomingWebhook/64881ad2495941928a621ed1c7ce1baa/273ef0d1-397e-469b-b601-0b07a650d12a
        title: 'Elastic-Agent en {{ inventory_hostname }} {{ elastic_status.output[0]}}'
        text: '{{ elastic_status.output }}'
      delegate_to: localhost
