---
- name: Configure VPN on FortiGate using HTTPAPI
  hosts: fortigates
  gather_facts: no
  collections:
    - fortinet.fortios
  vars: 
      local_gw: "192.168.1.13"
      remote_gw: "192.168.2.11"
      psksecret: "PruebasMilton123"
      name_phase1: "vpn_phase1"
      int_id: "port1"
      name_phase2: "vpn_phase2"
      lan_subnet1: "192.168.3.0/24"
      lan_subnet2: "192.168.4.0/24" 
      objects_name1: "red-harso"
      objects_name2: "red-corpo" 
      
      # Definición de los objetos que se crearán
      firewall_addresses1:
          - name: "{{ objects_name1 }}-local1"
            subnet: "{{ lan_subnet1 }}"
            type: "subnet"
            comment: "Subred local para Harso"
          - name: "{{ objects_name2 }}-remota1"
            subnet: "{{ lan_subnet2 }}"
            type: "subnet"
            comment: "Dirección para la lan remota del corporativo"

      firewall_addresses2:
          - name: "{{ objects_name2 }}-local1"
            subnet: "{{ lan_subnet2 }}"
            type: "subnet"
            comment: "Subred local para Corp"
          - name: "{{ objects_name1 }}-remota1"
            subnet: "{{ lan_subnet1 }}"
            type: "subnet"
            comment: "Dirección para la lan remota de Harso"      
    
  tasks:
  #Configura los peers
    - name: Configure IPsec Phase 1 Interface fw1
      fortios_vpn_ipsec_phase1_interface:
        vdom: "root"
        state: "present"
        vpn_ipsec_phase1_interface:
          name: "{{ name_phase1 }}"
          interface: "{{ int_id }}"
          local_gw:   "{{ local_gw }}"                
          remote_gw: "{{ remote_gw }}"
          psksecret: "{{ psksecret }}"
          type: "static"
          keylife: "28800"
          peertype: "any"
          net_device: "enable"
          proposal: "aes256-sha1"
      when: ansible_host == local_gw

    - name: Configure IPsec Phase 1 Interface fw2
      fortios_vpn_ipsec_phase1_interface:
        vdom: "root"
        state: "present"
        vpn_ipsec_phase1_interface:
          name: "{{ name_phase1 }}"
          interface: "{{ int_id }}"
          local_gw:   "{{ remote_gw }}"                
          remote_gw: "{{ local_gw }}"
          psksecret: "{{ psksecret }}"
          type: "static"
          keylife: "28800"
          peertype: "any"
          net_device: "enable"
          proposal: "aes256-sha1"
      when: not  ansible_host == local_gw        

#Configura la vpn
    - name: Configure IPsec Phase 2 Interface ambos fw1
      fortios_vpn_ipsec_phase2_interface:
        vdom: "root"
        state: "present"
        vpn_ipsec_phase2_interface:
          phase1name: "{{ name_phase1 }}"
          name: "{{ name_phase2 }}"
          src_name: "redes-locales"
          dst_name: "redes-remotas"
          proposal: "aes256-sha1"
          pfs: "enable"
          keylifeseconds: "3600"
  
  #Crea objetos de las redes locales y remotas 
    - name: Crear múltiples objetos de dirección IP para fw1
      fortios_firewall_address:
        vdom: "root"
        state: "present"
        firewall_address: "{{ item }}"
      loop: "{{ firewall_addresses1 }}"
      when: ansible_host == local_gw
    
    - name: Crear múltiples objetos de dirección IP para fw1
      fortios_firewall_address:
        vdom: "root"
        state: "present"
        firewall_address: "{{ item }}"
      loop: "{{ firewall_addresses2 }}"
      when: not ansible_host == local_gw
    

  #Crea objetos de las redes locales y remotas y las meta a un grupo
    - name: Create multiple address groups fw1
      fortios_firewall_addrgrp:
        vdom: "root"
        state: "present"
        firewall_addrgrp:
          name: "{{ item.name }}"
          member: "{{ item.member }}"
          comment: "{{ item.comment }}"
      with_items:
        - name: "redes-locales1"
          member:
            - "{{objects_name1}}-local1"
          comment: "Grupo que incluye la subred local"

        - name: "redes-remotas"
          member:
            - "{{objects_name2}}-remota1"
          comment: "Grupo que incluye la subred corporativa"
      when: ansible_host ==  local_gw

    - name: Create multiple address groups fw2
      fortios_firewall_addrgrp:
        vdom: "root"
        state: "present"
        firewall_addrgrp:
          name: "{{ item.name }}"
          member: "{{ item.member }}"
          comment: "{{ item.comment }}"
      with_items:
        - name: "redes-locales1"
          member:
            - "{{objects_name2}}-local1"
          comment: "Grupo que incluye la subred local"

        - name: "redes-remotas"
          member:
            - "{{objects_name1}}-remota1"
          comment: "Grupo que incluye la subred corporativa"
      when: not ansible_host ==  local_gw

#Crear ruta estatica entre las lans  (una que vaya haci la red-lan remota usando la vpn)
# y otra la por defecto para que el trafico lo mande a internet
    - name: Configure a static route fw1
      fortios_router_static:
        vdom: "root"
        state: "present"
        router_static:
          seq_num: 10  
          dst: "{{ lan_subnet1 }}" 
          #gateway: "192.168.1.1"  
          device: "{{ name_phase1 }}"  
          comment: "Ruta estática a la red 192.168.2.0/24" 
      when: ansible_host == local_gw
    
    - name: Configure a static route fw2
      fortios_router_static:
        vdom: "root"
        state: "present"
        router_static:
          seq_num: 10  
          dst: "{{ lan_subnet2 }}" 
          #gateway: "{{ name_phase1  }}"  
          device: "{{ name_phase1 }}"  
          comment: "Ruta estática a la red 192.168.2.0/24" 
      when: not ansible_host == local_gw
         
 #Falta crear la poltica bidireccional. (que vaya hacia las redes remotas y viceversa) desactivando NAT   
    - name: Create a firewall policy to allow VPN traffic fw1
      fortios_firewall_policy:
        vdom: "root"
        state: "present"
        firewall_policy:
          policyid: "7"
          name: "Poltica pruebas automatizacion"
          nat: "disable"
          action: "accept"
          schedule: "always"
          srcintf: 
           - name: "vpn_phase1"
          dstintf: 
           - name: "port1"
          srcaddr:
           - 
             name: "redes-locales"  # name: "red-corpo-remota" algo esta causando el any
          dstaddr: 
           - 
            name: "redes-remotas"  # name: "red-harso-remota"
          service: 
           - name: "ALL"
