---
- name: Configure VPN on FortiGate using HTTPAPI
  hosts: fortigates
  gather_facts: no
  collections:
    - fortinet.fortios

  tasks:
    - name: Configure IPsec Phase 1 Interface
      fortios_vpn_ipsec_phase1_interface:
        vdom: "root"
        state: "present"
        #access_token: "your_access_token"
        vpn_ipsec_phase1_interface:
          name: "vpn_phase1"
          type: "static"
          interface: "port1"
          local_gw: "192.168.1.12"
          remote_gw: "203.0.113.1"
          keylife: "28800"
          peertype: "any"
          net_device: "enable"
          proposal: "aes256-sha1"
          psksecret: "yourPresharedKey"

    - name: Configure IPsec Phase 2 Interface
      fortios_vpn_ipsec_phase2_interface:
        vdom: "root"
        state: "present"
       # access_token: "your_access_token"
        vpn_ipsec_phase2_interface:
          phase1name: "vpn_phase1"
          name: "vpn_phase2"
          proposal: "aes256-sha1"
          pfs: "enable"
          keylifeseconds: "3600"

    - name: Create a firewall policy to allow VPN traffic
      fortios_firewall_policy:
        vdom: "root"
        state: "present"
        #access_token: "your_generated_access_token" cx
        firewall_policy:
          policyid: 1
          name: "VPN to Internal"
          srcintf: 
            - "vpn_phase1"
          dstintf: 
            - "port1"
          srcaddr:
            - "all"
          dstaddr:
            - "all"
          action: "accept"
          schedule: "always"
          service:
            - "ALL"
          nat: "enable"

