---
- name: Recuperar el archivo de backup de un FortiGate y guardarlo en un servidor TFTP
  hosts: fortigates
  gather_facts: no
  collections:
    - fortinet.fortios
  tasks:
    - name: Realizar backup de la configuración y enviarlo al servidor TFTP
      fortios_system_config:
        vdom: "root"  # Cambiar si utilizas un VDOM diferente
        backup: "enable"
        tftp_server: "192.168.10.46"  # IP del servidor TFTP
        filename: "backup_fortigate.cfg"  # Nombre del archivo de respaldo
      register: backup_result

    - name: Verificar el resultado del backup
      debug:
        var: backup_result
