---
- name: Respaldar la configuración de FortiGate a un servidor TFTP
  hosts: fortigates
  gather_facts: no
  tasks:
    - name: Obtener la fecha actual
      delegate_to: localhost
      ansible.builtin.date:
        format: "%Y-%m-%d"  # Formato de fecha: Año-Mes-Día
      register: current_date

    - name: Mostrar la fecha actual
      debug:
        var: current_date
    - name: Ejecutar comando para hacer backup al servidor TFTP
      ansible.builtin.command:
        cmd: "execute backup config tftp backup_fortigate.conf 172.25.10.48"
      environment:
       ANSIBLE_HOST_KEY_CHECKING: "False" 
      register: backup_result
  
    - name: Mostrar el resultado del backup
      debug:
        var: backup_result
