---
- name: Respaldar la configuración de FortiGate a un servidor TFTP
  hosts: forti-pruebas
  gather_facts: no
  tasks:
    - name: Obtener la fecha actual
      ansible.builtin.shell: "date +'%Y-%m-%d'"
      register: current_date
      delegate_to: localhost

    - name: Mostrar la fecha actual
      debug:
        var: current_date.stdout
    
    - name: Ejecutar comando para hacer backup al servidor TFTP usando raw
      command: "execute backup config tftp /RESPALDOS_AWX/backup_fortigate-{{current_date.stdout}}.conf 172.19.51.11"
      register: backup_result
  
    - name: Mostrar el resultado del backup

      debug:
        var: backup_result.stdout
