---
- name: Respaldar la configuración de FortiGate a un servidor TFTP
  hosts: fortigates
  gather_facts: no
  tasks:
    - name: Obtener la fecha actual
      ansible.builtin.shell: "date +'%Y-%m-%d'"
      register: current_date
      delegate_to: localhost

    - name: Mostrar la fecha actual
      debug:
        var: current_date.stdout
    
    - name: Ejecutar comando para hacer backup al servidor TFTP usando raw
      vars: 
       ansible_connection: ssh
       ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
      raw: "execute backup config tftp /RESPALDOS_AWX/backup_fortigate-{{ ansible_host }}-{{current_date.stdout}}.conf 172.25.10.47"
      register: backup_result
  
    - name: Mostrar el resultado del backup

      debug:
        var: backup_result.stdout
