- name: Configure FortiGate with Ansible
  hosts: fortigate
  gather_facts: no


  tasks:
    - name: Retrieve FortiGate system status
      fortios_system_status:
        vdom: "root"
      register: result

    - name: Print the system status
      debug:
        var: result
