---
- name: Configure FortiGate with Ansible
  hosts: fortigates
  collection: 
    - name: fortinet.fortios
  gather_facts: no
  vars:
   vdom: "root"
  tasks:
  - name: Configure API users.
    fortios_system_global:
       vdom: "{{vdom}}"
       system_global:
         admintimeout: "23"
         hostname: "FortigateMilton-final"
