---
- name: Configure FortiGate with Ansible
  hosts: fortigates
  gather_facts: no
  #collections:
   #- fortinet.fortios
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: no
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 80
  tasks:
  - name: Configure API users.
    fortios_system_global:
       vdom: "{{vdom}}"
       system_global:
         admintimeout: "23"
         hostname: "FortigateMilton1"
