- name: Configure FortiGate with Ansible
  hosts: all
  gather_facts: yes
  collections:
    - fortinet.fortios
  tasks:
    - name: Retrieve FortiGate system status
      fortios_application_name:
      register: result

    - name: Print the system status
      debug:
        var: result
