---
- name: Instalacion de agente elastic
  hosts: localhost
  tasks:
    - name: Send notification message via MS Teams
      community.general.office_365_connector_card:
        webhook: https://harsomx.webhook.office.com/webhookb2/bf693546-8702-4185-9fbe-2ea27a6b65d7@40b6f753-6e95-4c0a-bd92-a9fcb653746a/IncomingWebhook/64881ad2495941928a621ed1c7ce1baa/273ef0d1-397e-469b-b601-0b07a650d12a
        text: 'Hello, World!'
      delegate_to: localhost
      register: mensaje

    - name: debug
      ansible.builtin.debug:
        msg: '{{ mensaje }}'

- name: Send notification message via MS Teams
      community.general.office_365_connector_card:
        webhook: https://harsomx.webhook.office.com/webhookb2/bf693546-8702-4185-9fbe-2ea27a6b65d7@40b6f753-6e95-4c0a-bd92-a9fcb653746a/IncomingWebhook/64881ad2495941928a621ed1c7ce1baa/273ef0d1-397e-469b-b601-0b07a650d12a
        title: 'Elastic-Agent en {{ inventory_hostname }} {{ elastic_status.output[0]}}'
        color: E81123
        text: '{{ elastic_status.output | to_nice_yaml }}'
        summary: 'Alerta servidor {{ inventory_hostname }}'  # mensaje dentro de notificacion en feed
        sections:
        - title: 'Ansible playbook {{ ansible_play_name }}'
          activity_image: https://w7.pngwing.com/pngs/1013/808/png-transparent-windows-server-2012-r2-windows-server-2008-client-access-license-microsoft-blue-angle-text-thumbnail.png
          activity_title: 'Server Name: **{{ inventory_hostname }}**'
          activity_subtitle: 'Server IP: **{{ ansible_host }}**'
          activity_text: 
          text: 'Datos del Servidor:' # '{{ elastic_status | json_query("output[*]") | flatten }}'
          facts:
          - name: Estado de cpu
            value: '98%'
          - name: conectividad a fleet server
            value: 'yes'
          - name: conectividad a ElasticSearch
            value: 'yes'
          actions:
          - "@type": OpenUri
            name: RDP to Server
            targets:
            - os: default
              uri: rdp://
          - "@type": OpenUri
            name: Entrar a AWX
            targets:
            - os: default
              uri: http://10.1.2.204/
      delegate_to: localhost


rdp://172.25.10.25=s:mypc:3389&audiomode=i:2&disable%20themes=i:1