---
- name: Instalacion de agente elastic
  hosts: localhost
  tasks:
    - name: Send notification message via MS Teams
      community.general.office_365_connector_card:
        webhook: https://harsomx.webhook.office.com/webhookb2/bf693546-8702-4185-9fbe-2ea27a6b65d7@40b6f753-6e95-4c0a-bd92-a9fcb653746a/IncomingWebhook/64881ad2495941928a621ed1c7ce1baa/273ef0d1-397e-469b-b601-0b07a650d12a
        text: 'Hello, World!'
      delegate_to: localhost
      register: mensaje

    - name: debug
      ansible.builtin.debug:
        msg: '{{ mensaje }}'
