---
- name: Instalacion de agente elastic
  hosts: localhost
  tasks:
    - name: Test Script
      ansible.builtin.debug: # El usuario tiene que tener privilegio SYSTEM | HIGH, SeDebugPrivilege: enabled y rights: SeBatchLogonRight | SeNetworkLogonRight
        msg: |
          $ProgressPreference = 'SilentlyContinue'
          cd C:\Temp
          Invoke-WebRequest -Uri https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.4.1-windows-x86_64.zip `
          -OutFile elastic-agent-8.4.1-windows-x86_64.zip
          Expand-Archive .\elastic-agent-8.4.1-windows-x86_64.zip -DestinationPath .
          cd elastic-agent-8.4.1-windows-x86_64
          .\elastic-agent.exe install --non-interactive --url=https://hso-fleet-server-agent-http.hsoelk.svc:8220 `
          --enrollment-token=bzRMb2dJTUI0by1fTWZSMU8td0k6eVVSX1pDSHBUTnlBQlJIWEtEUDd5UQ==
