---
- name: Instalación de agente Elastic en Linux
  hosts: all
  vars:
    fleetserver_fqdn: 'https://fleetserver.harso.com:8220'
    elastic_version: '8.13.4'
    enrollment_token: 'YTBFN2w0OEIwWXhlYVV2VEFyblY6NzdTT2JQLW9UeW10Nmo2YVhWa092QQ=='
    msteams_webhook: 'https://harsomx.webhook.office.com/webhookb2/bf693546-8702-4185-9fbe-2ea27a6b65d7@40b6f753-6e95-4c0a-bd92-   a9fcb653746a/IncomingWebhook/ed378f885ded4004ad39cc313f896e94/acaf0036-6402-4a6d-a50d-252ae0cbc883'
    awx_url: 'http://10.1.1.15/'
  tasks:
    - name: Validar si el agente de Elastic está instalado
      command: ps -ef | grep -v grep | grep "elastic-agent"
      register: elastic
      ignore_errors: true

    - name: Crear estructura de directorios
      file:
        path: /tmp/elastic-agent
        state: directory

    - name: Descargar y extraer el agente Elastic
      shell: |
        cd /tmp/elastic-agent
        curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-{{elastic_version}}-linux-x86_64.tar.gz
        tar xzvf elastic-agent-{{elastic_version}}-linux-x86_64.tar.gz
        when: not elastic.stdout

    - name: Instalar el agente Elastic
      shell: |
      cd elastic-agent-{{elastic_version}}-linux-x86_64
      sudo ./elastic-agent install --url= "{{ fleetserver_fqdn }}" --enrollment-token="{{ enrollment_token }}"
      when: not elastic.stdout

    - name: Eliminar contenido del directorio temporal
      file:
        path: /tmp/elastic-agent
        state: absent

    - name: Enviar notificacion por MS Teams
      community.general.office_365_connector_card:
        webhook: '{{ msteams_webhook }}'
        title: 'Resultados de instalacion de agentes en {{ inventory_hostname }}'
        color: |
          {% if install.output[1] | default('failed') == 'Elastic Agent has been successfully installed.' %}
          23E811
          {% else %}
          E81123
          {% endif %}
        summary: 'Notificacion servidor {{ inventory_hostname }}' # Mensaje en notificacion PopUp
        sections:
          - title: 'Ansible playbook: **{{ ansible_play_name }}**'
            start_group: true
            activity_image: https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png
            activity_title: 'Server Name: **{{ ansible_facts.hostname }}**'
            activity_subtitle: 'Server IP: **{{ ansible_host }}**'
            activity_text:
            text: 'Instalacion de agente:'
            facts:
              - name: 'Status:'
                value: "{{ install.output | join(' ') }}"
            actions:
              - "@type": OpenUri
                name: RDP to Server
                targets:
                  - os: default
                    uri: 'rdp://{{ ansible_host }}=s:localhost'
              - "@type": OpenUri
                name: Entrar a AWX
                targets:
                  - os: default
                    uri: '{{ awx_url }}'
      delegate_to: localhost
