---
- name: Desistalación de agente Elastic en Linux
  hosts: all
  vars:
    uninstall_token: 'ca3b3d9a0f0a81decf58f277fb2646ee'
    msteams_webhook: 'https://harsomx.webhook.office.com/webhookb2/bf693546-8702-4185-9fbe-2ea27a6b65d7@40b6f753-6e95-4c0a-bd92-a9fcb653746a/IncomingWebhook/ed378f885ded4004ad39cc313f896e94/acaf0036-6402-4a6d-a50d-252ae0cbc883'
    awx_url: 'http://10.1.1.15/'
    service_name: ['elastic-agent.service' , 'ElasticEndpoint.service', 'hola']
 
  tasks:
#Se recuperan los servicios dentro en el sistema
    - name: Obtener detalles del servicio
      ansible.builtin.service_facts:

    - name: Guardar Servicios existentes
      set_fact:
        servicios: "{{ servicios | default({}) | combine( { item: ansible_facts.services[item]  }   )    }}"
      when: item in ansible_facts.services
      loop: "{{ service_name  }}"

    - name: Imprimir resultado array
      ansible.builtin.debug:
       var: servicios

   
   #Solo borrara agente elastic endpoint      
   # - name: Desinstalar Elastic Defend
   #   become: true
   #   shell: |
   #    cd /tmp
   #    cp /opt/Elastic/Endpoint/elastic-endpoint elastic-endpoint
   #    sudo ./elastic-endpoint uninstall
   #    rm elastic-endpoint
   #   when: service_name[1] in servicios 

  #Borra todo los servicios que esten ligados a elastic agent
    - name: Desinstalar Elastic Agent
      become: true
      command: sudo /opt/Elastic/Agent/elastic-agent uninstall --force
      when: service_name[0] in servicios

         
    - name: Desinstalar Elastic Agent
      become: true
      command: sudo elastic-agent uninstall --uninstall-token {{uninstall_token}} --force    
      swhen: service_name[0] in servicios

    - name: Verificar si el archivo existe
      become: true
      ansible.builtin.stat:
        path: /opt/Elastic/Agent
      register: resultado
 
    - name: Enviar notificacion por MS Teams
      delegate_to: localhost
      community.general.office_365_connector_card:
        webhook: '{{ msteams_webhook }}'
        title: 'Resultados de eliminacion de agentes en {{ ansible_facts.hostname }}'
        color: |
          {% if resultado.stat.exists %}
          E81123
          {% else %}
          23E811
          {% endif %}
        summary: 'Notificacion servidor {{ ansible_facts.hostname }}' # Mensaje en notificacion PopUp
        sections:
          - title: 'Ansible playbook: **{{ ansible_play_name }}**'
            start_group: true
            activity_image: https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png
            activity_title: 'Server Name: **{{ ansible_facts.hostname }}**'
            activity_subtitle: 'Server IP: **{{ ansible_host }}**'
            activity_text:
            text: 'Datos de agentes:'
            facts:
              - name: 'Elastic Agent:'
                value: |
                 {% if service_name[0] in servicios %}
                  Agente desinstalado correctamente
                  {% elif service.results[0].exists and service_status.results[0].failed %}
                  {% else %}
                  Agente NO desinstalado (ERROR)
                  {% endif %}
            actions:
              - "@type": OpenUri
                name: RDP to Server
                targets:
                  - os: default
                    uri: 'rdp://{{ ansible_host }}=s:localhost'
              - "@type": OpenUri
                name: Entrar a AWX
                targets:
                  - os: default
                    uri: '{{ awx_url }}'
     
