---
- name: Playbook Principal
  hosts: all
  vars:
    condition1: true
    condition2: false
  tasks:
    - name: Incluir playbook1 si condition1 es true
      import_playbook: playbook1.yml
      when: condition1

    - name: Incluir playbook2 si condition2 es true
      import_playbook: playbook2.yml
      when: condition2