---
- name: Playbook Principal
  hosts: all
  gather_facts: false
  vars:
    condition1: true
    condition2: false
    fleetserver_fqdn: 'fleetserver.harso.com'
    elastic_version: '8.13.4' 
    enrollment_token: 'YTBFN2w0OEIwWXhlYVV2VEFyblY6NzdTT2JQLW9UeW10Nmo2YVhWa092QQ=='
    msteams_webhook: 'https://harsomx.webhook.office.com/webhookb2/bf693546-8702-4185-9fbe-2ea27a6b65d7@40b6f753-6e95-4c0a-bd92-a9fcb653746a/IncomingWebhook/ed378f885ded4004ad39cc313f896e94/acaf0036-6402-4a6d-a50d-252ae0cbc883'
    awx_url: 'http://10.1.1.15/'
  tasks:
    - name: Incluir playbook1 si condition1 es true
      import_tasks: playbook1.yml
      when: condition1

    - name: Incluir playbook2 si condition2 es true
      import_tasks: playbook2.yml
      when: condition2