---
#Versiones ubuntu 20.04-22.04
- name: playbook1
  hosts: all
  gather_facts: true
  vars: 
    url_installer: 'https://console.amp.cisco.com/install_packages/9c8c009f-99e8-40c2-8b05-ab03551e80ae/download?product=LinuxProduct&product_variant_id=a1ef784e-3aea-41ae-8725-9d4ad08eb4ea'
    local_installer_path: '/tmp/cse-agent/amp_Monitoreo_Semanal_ubuntu-20-04-amd64.deb'
    ansible_user: pruebasubuntu
    ansible_password: Emalacm1pt$
  tasks:
    - name: Verificar sistema operativo
      debug:
        msg: "El sistema operativo que está instalado es {{ ansible_os_family }}"

    - name: Instalar curl si no está instalado
      become: true
      apt:
        name: curl
        state: present    

    - name: Crear estructura de directorios
      become: true
      file:
        path: /tmp/cse-agent
        state: directory
     
    - name: Descargar el paquete .deb
      become: true
      get_url:
        url: "{{ url_installer }}"
        dest: "{{ local_installer_path }}"

    - name: Instalar el paquete .deb
      become: true
      apt:
        deb: "{{ local_installer_path }}"
        state: present

    - name: Eliminar contenido del directorio temporal
      become: true
      file:
        path: /tmp/cse-agent
        state: absent
        recurse: yes

