---
#Versiones ubuntu 20.04-22.04
- name: playbook1
  hosts: Pruebas-CSE
  gather_facts: false
  vars: 
    url_installer: 'https://console.amp.cisco.com/install_packages/393061cf-f40a-4153-8b7f-2fbbe453ed6a/download?product=LinuxProduct&product_variant_id=a1ef784e-3aea-41ae-8725-9d4ad08eb4ea'
    local_installer_path: '/tmp/cse-agent/amp_Monitoreo_Semanal_ubuntu-20-04-amd64.deb'
    become: true
  tasks:
    - name: Verificar sistema operativo
      debug:
        msg: "El sistema operativo que está instalado es {{ ansible_os_family }}"

    - name: Instalar curl si no está instalado
      apt:
        name: curl
        state: present    

    - name: Crear estructura de directorios
      file:
        path: /tmp/cse-agent
        state: directory
     
    - name: Descargar el paquete .deb
      get_url:
        url: "{{ url_installer }}"
        dest: "{{ local_installer_path }}"

    - name: Instalar el paquete .deb
      apt:
        deb: "{{ local_installer_path }}"
        state: present

    - name: Eliminar contenido del directorio temporal
      file:
        path: /tmp/cse-agent
        state: absent
        recurse: yes

